CREATE TABLE FUNCIONARIO(
    Pnome VARCHAR(255) NOT NULL,
    Minicial CHAR(1) NOT NULL,
    Unome VARCHAR(255) NOT NULL,
    Datanasc DATE NOT NULL, 
    Endereco VARCHAR(255) NOT NULL,
    Cpf CHAR(11) NOT NULL,
    Sexo CHAR(1) NOT NULL,
    Salario FLOAT NOT NULL,
    Cpf_supervisor CHAR(11) NULL,
    Dnr INT NOT NULL,
    PRIMARY KEY (Cpf)
);
     
ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FOREIGN KEY (Cpf_supervisor) REFERENCES FUNCIONARIO (Cpf)
    
ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FOREIGN KEY (Dnr) REFERENCES DEPARTAMENTO (Dnumero)   

CREATE TABLE DEPARTAMENTO(    
    Dnome VARCHAR(255) NOT NULL,
    Dnumero INT NOT NULL,
    Cpf_gerente CHAR(11) NOT NULL,
    Data_inicio_gerente DATE NOT NULL, 
    UNIQUE KEY (Cpf_gerente),
    PRIMARY KEY (Dnumero)    
);

ALTER TABLE DEPARTAMENTO
    ADD CONSTRAINT FOREIGN KEY (Cpf_gerente) REFERENCES FUNCIONARIO (Cpf)   

CREATE TABLE LOCALIZACOES_DEP(
    Dnumero INT,
    Dlocal VARCHAR(255) NOT NULL    
);

ALTER TABLE LOCALIZACOES_DEP
    ADD CONSTRAINT FOREIGN KEY (Dnumero) REFERENCES DEPARTAMENTO (Dnumero)

CREATE TABLE PROJETO(    
    Projnome VARCHAR(255) NOT NULL,
    Projnumero INT NOT NULL,
    Projlocal VARCHAR(255) NOT NULL,
    Dnum INT NOT NULL,
    PRIMARY KEY (Projnumero)        
);

ALTER TABLE PROJETO
    ADD CONSTRAINT FOREIGN KEY (Dnum) REFERENCES DEPARTAMENTO (Dnumero)

CREATE TABLE TRABALHA_EM( 
    Fcpf CHAR(11) NOT NULL,
    Pnr INT NOT NULL,
    Horas DECIMAL(3,1) NULL  
);

ALTER TABLE TRABALHA_EM
    ADD CONSTRAINT FOREIGN KEY (Fcpf) REFERENCES FUNCIONARIO (Cpf),
    ADD CONSTRAINT FOREIGN KEY (Pnr) REFERENCES PROJETO (Projnumero);

CREATE TABLE DEPENDENTE( 
    Fcpf CHAR(11) NOT NULL,
    Nome_dependente VARCHAR(255) NOT NULL,
    Sexo CHAR(1) NOT NULL,
    Datanasc DATE NOT NULL, 
    Parentesco VARCHAR(255) NOT NULL
);

ALTER TABLE DEPENDENTE
    ADD CONSTRAINT FOREIGN KEY (Fcpf) REFERENCES FUNCIONARIO (Cpf)